# Generated from the pinned vv-agent-contract builtin_tools fixture.
# Run `uv run python scripts/generate_builtin_tool_schemas.py` after contract_snapshot.py sync.
# Do not edit this file by hand.
# ruff: noqa: E501
from __future__ import annotations

from copy import deepcopy
from typing import Any

from vv_agent.constants.tool_names import (
    ACTIVATE_SKILL_TOOL_NAME,
    ASK_USER_TOOL_NAME,
    EDIT_FILE_TOOL_NAME,
    FILE_INFO_TOOL_NAME,
    FIND_FILES_TOOL_NAME,
    READ_FILE_TOOL_NAME,
    SEARCH_FILES_TOOL_NAME,
    TODO_WRITE_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
)

ToolSchema = dict[str, Any]

WORKSPACE_TOOLS = [
    FIND_FILES_TOOL_NAME,
    FILE_INFO_TOOL_NAME,
    READ_FILE_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
    EDIT_FILE_TOOL_NAME,
    SEARCH_FILES_TOOL_NAME,
    TODO_WRITE_TOOL_NAME,
]

_DEFAULT_TOOL_SCHEMAS: dict[str, ToolSchema] = {
    "ask_user": {
        "type": "function",
        "function": {
            "name": "ask_user",
            "description": "Pause for a required user decision that cannot be discovered safely with available tools. Ask one concrete question and provide concise options when useful.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "allow_custom_options": {"description": "Whether users can add custom options.", "type": "boolean"},
                    "options": {
                        "description": "Optional answer options shown to the user.",
                        "items": {"type": "string"},
                        "type": "array",
                    },
                    "question": {"description": "Question text to ask the user.", "type": "string"},
                    "selection_type": {
                        "description": "Single or multi-choice mode when options are provided.",
                        "enum": ["single", "multi"],
                        "type": "string",
                    },
                },
                "required": ["question"],
                "type": "object",
            },
        },
    },
    "activate_skill": {
        "type": "function",
        "function": {
            "name": "activate_skill",
            "description": "Load one skill listed in the current available-skills metadata. Use the exact skill name and follow the returned instructions; unlisted names are rejected.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "reason": {"description": "Optional reason for activating this skill.", "type": "string"},
                    "skill_name": {"description": "Skill identifier from available skill list.", "type": "string"},
                },
                "required": ["skill_name"],
                "type": "object",
            },
        },
    },
    "todo_write": {
        "type": "function",
        "function": {
            "name": "todo_write",
            "description": "Replace the current structured TODO list. Send the complete list, keep at most one item in_progress, and use stable ids when updating existing items.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "todos": {
                        "description": "Complete TODO list replacement payload.",
                        "items": {
                            "additionalProperties": False,
                            "properties": {
                                "id": {
                                    "description": "Existing TODO id for update; omit for new item. When omitted, a generated 8-character id is assigned.",
                                    "type": "string",
                                },
                                "priority": {
                                    "description": "TODO priority: `high` for blockers or user-critical work, `medium` for normal required work, `low` for cleanup or optional follow-up.",
                                    "enum": ["low", "medium", "high"],
                                    "type": "string",
                                },
                                "status": {
                                    "description": "TODO status: `pending` for not started, `in_progress` for the single active item, or `completed` after verification.",
                                    "enum": ["pending", "in_progress", "completed"],
                                    "type": "string",
                                },
                                "title": {
                                    "description": "TODO title. Make it actionable and observable, so progress can be verified without reading hidden context.",
                                    "type": "string",
                                },
                            },
                            "required": ["title", "status", "priority"],
                            "type": "object",
                        },
                        "type": "array",
                    }
                },
                "required": ["todos"],
                "type": "object",
            },
        },
    },
    "find_files": {
        "type": "function",
        "function": {
            "name": "find_files",
            "description": "List workspace files with path, glob, visibility, pagination, and sorting controls. Results are bounded and report truncation/count hints; paths remain subject to workspace policy.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "glob": {"description": "Optional glob filter such as `**/*.py`.", "type": "string"},
                    "include_hidden": {"description": "Whether hidden files and dotfiles are included.", "type": "boolean"},
                    "include_ignored": {
                        "description": "When listing workspace root, include files under common dependency/cache directories.",
                        "type": "boolean",
                    },
                    "include_sensitive": {
                        "description": "Include files whose paths look like secrets, credentials, keys, tokens, or private config.",
                        "type": "boolean",
                    },
                    "max_results": {"description": "Maximum number of file paths returned in one call.", "type": "integer"},
                    "offset": {
                        "description": "Number of matching file paths to skip before returning results.",
                        "minimum": 0,
                        "type": "integer",
                    },
                    "path": {"description": "Optional search root path.", "type": "string"},
                    "scan_limit": {
                        "description": "Maximum files scanned before stopping early to keep listing fast.",
                        "type": "integer",
                    },
                    "sort": {"description": "Sort order.", "enum": ["modified_desc", "path_asc"], "type": "string"},
                },
                "required": [],
                "type": "object",
            },
        },
    },
    "file_info": {
        "type": "function",
        "function": {
            "name": "file_info",
            "description": "Inspect workspace path metadata without reading file contents. Returns normalized type, size, modified time, suffix, and line-count information when available.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "path": {
                        "description": "Target file path (workspace-relative by default; absolute path allowed when outside-workspace access is enabled).",
                        "type": "string",
                    }
                },
                "required": ["path"],
                "type": "object",
            },
        },
    },
    "read_file": {
        "type": "function",
        "function": {
            "name": "read_file",
            "description": "Read bounded UTF-8 text from a workspace path. Use a line range for targeted reads or the returned cursor to continue an oversized read; stale cursors are rejected if the source changes.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "end_line": {
                        "description": "Optional 1-based inclusive last line; incompatible with cursor.",
                        "minimum": 1,
                        "type": "integer",
                    },
                    "path": {"description": "Workspace path to read.", "type": "string"},
                    "show_line_numbers": {"description": "Prefix returned lines with source line numbers.", "type": "boolean"},
                    "start_line": {
                        "description": "Optional 1-based first line; incompatible with cursor.",
                        "minimum": 1,
                        "type": "integer",
                    },
                    "cursor": {
                        "additionalProperties": False,
                        "description": "Continuation state returned by a previous read of this path.",
                        "properties": {
                            "kind": {"const": "read_file", "type": "string"},
                            "offset_chars": {"minimum": 0, "type": "integer"},
                            "path": {"minLength": 1, "type": "string"},
                            "sha256": {"pattern": "^[0-9a-f]{64}$", "type": "string"},
                        },
                        "required": ["kind", "offset_chars", "path", "sha256"],
                        "type": "object",
                    },
                },
                "required": ["path"],
                "type": "object",
            },
        },
    },
    "write_file": {
        "type": "function",
        "function": {
            "name": "write_file",
            "description": "Create, overwrite, or append text in the workspace. Overwrite is the default; use append and newline controls only when preserving existing content is intentional.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "append": {"description": "Set true to append instead of overwrite.", "type": "boolean"},
                    "content": {
                        "description": "The complete file body for overwrite mode, or the exact block to append when `append=true`.",
                        "type": "string",
                    },
                    "leading_newline": {"description": "Add a leading newline when appending.", "type": "boolean"},
                    "path": {
                        "description": "Target file path (workspace-relative by default; absolute path allowed when outside-workspace access is enabled).",
                        "type": "string",
                    },
                    "trailing_newline": {"description": "Add a trailing newline when appending.", "type": "boolean"},
                },
                "required": ["path", "content"],
                "type": "object",
            },
        },
    },
    "edit_file": {
        "type": "function",
        "function": {
            "name": "edit_file",
            "description": "Replace exact text in a workspace file using the current read/write baseline. The match must be unique unless replace_all is true, and changed files or stale baselines are rejected.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "new_string": {"description": "Replacement text.", "type": "string"},
                    "old_string": {"description": "Exact source text to replace.", "type": "string"},
                    "path": {
                        "description": "Target file path (workspace-relative by default; absolute path allowed when outside-workspace access is enabled).",
                        "type": "string",
                    },
                    "replace_all": {
                        "description": "Replace all matches when true after confirming every match is intended.",
                        "type": "boolean",
                    },
                },
                "required": ["path", "old_string", "new_string"],
                "type": "object",
            },
        },
    },
    "search_files": {
        "type": "function",
        "function": {
            "name": "search_files",
            "description": "Search workspace text with regex and smart-case by default; set literal for exact text. Scope with path, glob, or type. Results are bounded and return truncation/pagination metadata.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "a": {"description": "Lines after each match.", "type": "integer"},
                    "b": {"description": "Lines before each match.", "type": "integer"},
                    "c": {"description": "Context lines before and after each match.", "type": "integer"},
                    "case_sensitive": {"description": "Explicitly override smart-case behavior.", "type": "boolean"},
                    "glob": {"description": "Optional file glob filter such as `**/*.rs`.", "type": "string"},
                    "head_limit": {"description": "Cap output to the first N rows or entries.", "minimum": 0, "type": "integer"},
                    "include_hidden": {"description": "Whether hidden files and dotfiles are included.", "type": "boolean"},
                    "include_ignored": {
                        "description": "When searching workspace root, include files under common dependency/cache directories.",
                        "type": "boolean",
                    },
                    "include_sensitive": {
                        "description": "Include files whose paths look like secrets, credentials, keys, tokens, or private config.",
                        "type": "boolean",
                    },
                    "literal": {
                        "description": "Search for the exact pattern text instead of interpreting it as a regex.",
                        "type": "boolean",
                    },
                    "multiline": {"description": "Enable multiline regex mode.", "type": "boolean"},
                    "n": {"description": "Whether to include line numbers in content output.", "type": "boolean"},
                    "offset": {
                        "description": "Number of result rows or entries to skip before returning results.",
                        "minimum": 0,
                        "type": "integer",
                    },
                    "output_mode": {
                        "description": "files_with_matches, content, or count.",
                        "enum": ["files_with_matches", "content", "count"],
                        "type": "string",
                    },
                    "path": {"description": "Optional search root or single file path.", "type": "string"},
                    "pattern": {"description": "Regex pattern, or exact text when literal is true.", "type": "string"},
                    "type": {"description": "File type shortcut such as py, js, ts, md, or json.", "type": "string"},
                },
                "required": ["pattern"],
                "type": "object",
            },
        },
    },
    "bash": {
        "type": "function",
        "function": {
            "name": "bash",
            "description": "Run a command in the configured workspace shell. Return its output when it exits within yield_time_ms, otherwise return a session_id and current output while it keeps running. Use check_background_command to inspect or stop_background_command to stop it. Oversized output has a recoverable workspace artifact.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "auto_confirm": {
                        "default": False,
                        "description": "Pipe yes to the command for non-interactive confirmation prompts.",
                        "type": "boolean",
                    },
                    "command": {"description": "Command to execute through the configured shell.", "type": "string"},
                    "exec_dir": {
                        "description": "Execution directory (workspace-relative by default; absolute path allowed when outside-workspace access is enabled).",
                        "type": "string",
                    },
                    "stdin": {
                        "description": "Optional stdin content for interactive prompts, confirmation text, heredoc-style input, or commands that read from standard input.",
                        "type": "string",
                    },
                    "yield_time_ms": {
                        "default": 1000,
                        "description": "Maximum initial wait in milliseconds. Zero returns a handle immediately. Reaching this wait does not stop the command.",
                        "minimum": 0,
                        "maximum": 10000,
                        "type": "integer",
                    },
                    "timeout_seconds": {
                        "description": "Optional execution limit in seconds from process start, including time after returning a handle. Omit for no execution deadline. Querying never extends it.",
                        "minimum": 1,
                        "maximum": 86400,
                        "type": "integer",
                    },
                },
                "required": ["command"],
                "type": "object",
            },
        },
    },
    "check_background_command": {
        "type": "function",
        "function": {
            "name": "check_background_command",
            "description": "Read the current state and bounded output of a command owned by this task and workspace. This is an immediate snapshot. A missing local session does not establish that its process exited. Oversized output includes a recoverable workspace artifact.",
            "parameters": {
                "additionalProperties": False,
                "properties": {"session_id": {"description": "Session id returned by bash.", "type": "string"}},
                "required": ["session_id"],
                "type": "object",
            },
        },
    },
    "stop_background_command": {
        "type": "function",
        "function": {
            "name": "stop_background_command",
            "description": "Stop the process tree of a command owned by this task and workspace. Returns bounded output and observed exit status after termination is confirmed; stopping or unknown means termination is not yet confirmed. A missing local session does not establish that its process exited.",
            "parameters": {
                "additionalProperties": False,
                "properties": {"session_id": {"description": "Session id returned by bash.", "type": "string"}},
                "required": ["session_id"],
                "type": "object",
            },
        },
    },
    "create_sub_task": {
        "type": "function",
        "function": {
            "name": "create_sub_task",
            "description": "Run one task, or independent batch tasks, on a configured sub-agent. Use the exact agent id, keep tasks self-contained, and choose background execution only when the parent can continue independently.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "agent_id": {
                        "description": "Exact sub-agent identifier from the configured `sub_agents` mapping.",
                        "type": "string",
                    },
                    "exclude_files_pattern": {
                        "description": "Optional portable regex applied to normalized workspace-relative paths for child discovery only.",
                        "type": "string",
                    },
                    "include_main_summary": {"description": "Whether to include parent-task summary context.", "type": "boolean"},
                    "output_requirements": {"description": "Optional output constraints for single-task mode.", "type": "string"},
                    "task_description": {
                        "description": "Single-task description for one self-contained objective.",
                        "type": "string",
                    },
                    "tasks": {
                        "description": "Batch mode: multiple independent tasks for the same sub-agent.",
                        "items": {
                            "additionalProperties": False,
                            "properties": {
                                "output_requirements": {
                                    "description": "Optional output constraints for one sub-task. State success criteria, expected format, concrete deliverables, and verification evidence.",
                                    "type": "string",
                                },
                                "task_description": {
                                    "description": "Task description for one independent sub-task. Give a concrete objective, relevant constraints, files or commands, and the evidence or deliverable expected by the parent Agent.",
                                    "type": "string",
                                },
                            },
                            "required": ["task_description"],
                            "type": "object",
                        },
                        "minItems": 1,
                        "type": "array",
                    },
                    "wait_for_completion": {"description": "Whether to wait for completion.", "type": "boolean"},
                },
                "required": ["agent_id"],
                "type": "object",
            },
        },
    },
    "sub_task_status": {
        "type": "function",
        "function": {
            "name": "sub_task_status",
            "description": "Inspect configured sub-task ids, optionally wait, or send one follow-up message to the first id. Snapshot mode adds recent activity and bounded workspace-file evidence.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "check_interval_seconds": {
                        "default": 300,
                        "description": "Optional.",
                        "maximum": 1800,
                        "minimum": 30,
                        "type": "integer",
                    },
                    "detail_level": {
                        "description": "Status response detail level.",
                        "enum": ["basic", "snapshot"],
                        "type": "string",
                    },
                    "max_wait_seconds": {
                        "default": None,
                        "description": "Optional.",
                        "maximum": 86400,
                        "minimum": 60,
                        "type": ["integer", "null"],
                    },
                    "message": {"description": "Optional follow-up or steering message for the first task id.", "type": "string"},
                    "task_ids": {
                        "description": "Sub-task ids to query.",
                        "items": {"type": "string"},
                        "minItems": 1,
                        "type": "array",
                    },
                    "wait_for_completion": {"default": False, "description": "Optional.", "type": "boolean"},
                    "wait_for_response": {
                        "description": "When `message` is provided, wait until the task finishes processing that message.",
                        "type": "boolean",
                    },
                    "workspace_file_limit": {
                        "description": "Maximum number of workspace files returned per task in snapshot mode.",
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                    },
                },
                "required": ["task_ids"],
                "type": "object",
            },
        },
    },
    "read_image": {
        "type": "function",
        "function": {
            "name": "read_image",
            "description": "Attach a supported workspace image or HTTP image URL to the next model turn. Local files remain subject to workspace policy, format checks, and the inline size limit.",
            "parameters": {
                "additionalProperties": False,
                "properties": {"path": {"description": "Image path or URL to attach.", "type": "string"}},
                "required": ["path"],
                "type": "object",
            },
        },
    },
}

ASK_USER_TOOL_SCHEMA: ToolSchema = _DEFAULT_TOOL_SCHEMAS[ASK_USER_TOOL_NAME]
ACTIVATE_SKILL_TOOL_SCHEMA: ToolSchema = _DEFAULT_TOOL_SCHEMAS[ACTIVATE_SKILL_TOOL_NAME]

_CONTROL_TOOL_NAMES = {
    ASK_USER_TOOL_NAME,
    ACTIVATE_SKILL_TOOL_NAME,
}
WORKSPACE_TOOLS_SCHEMAS: dict[str, ToolSchema] = {
    name: schema for name, schema in _DEFAULT_TOOL_SCHEMAS.items() if name not in _CONTROL_TOOL_NAMES
}


def get_default_tool_schemas() -> dict[str, ToolSchema]:
    return deepcopy(_DEFAULT_TOOL_SCHEMAS)
