#!/usr/bin/env python3
"""Generate the Python builtin tool schema source from the pinned contract snapshot."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from pprint import pformat

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FIXTURE = ROOT / "tests" / "fixtures" / "parity" / "builtin_tools.json"
DEFAULT_OUTPUT = ROOT / "src" / "vv_agent" / "constants" / "workspace.py"


HEADER = """# Generated from the pinned vv-agent-contract builtin_tools fixture.
# Run `uv run python scripts/generate_builtin_tool_schemas.py` after contract_snapshot.py sync.
# Do not edit this file by hand.
# ruff: noqa: E501
from __future__ import annotations

from copy import deepcopy
from typing import Any

from vv_agent.constants.tool_names import (
    ACTIVATE_SKILL_TOOL_NAME,
    ASK_USER_TOOL_NAME,
    EDIT_FILE_TOOL_NAME,
    FILE_INFO_TOOL_NAME,
    FIND_FILES_TOOL_NAME,
    READ_FILE_TOOL_NAME,
    SEARCH_FILES_TOOL_NAME,
    TASK_FINISH_TOOL_NAME,
    TODO_WRITE_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
)

ToolSchema = dict[str, Any]

WORKSPACE_TOOLS = [
    FIND_FILES_TOOL_NAME,
    FILE_INFO_TOOL_NAME,
    READ_FILE_TOOL_NAME,
    WRITE_FILE_TOOL_NAME,
    EDIT_FILE_TOOL_NAME,
    SEARCH_FILES_TOOL_NAME,
    TODO_WRITE_TOOL_NAME,
]

"""


FOOTER = """

TASK_FINISH_TOOL_SCHEMA: ToolSchema = _DEFAULT_TOOL_SCHEMAS[TASK_FINISH_TOOL_NAME]
ASK_USER_TOOL_SCHEMA: ToolSchema = _DEFAULT_TOOL_SCHEMAS[ASK_USER_TOOL_NAME]
ACTIVATE_SKILL_TOOL_SCHEMA: ToolSchema = _DEFAULT_TOOL_SCHEMAS[ACTIVATE_SKILL_TOOL_NAME]

_CONTROL_TOOL_NAMES = {
    TASK_FINISH_TOOL_NAME,
    ASK_USER_TOOL_NAME,
    ACTIVATE_SKILL_TOOL_NAME,
}
WORKSPACE_TOOLS_SCHEMAS: dict[str, ToolSchema] = {
    name: schema for name, schema in _DEFAULT_TOOL_SCHEMAS.items() if name not in _CONTROL_TOOL_NAMES
}


def get_default_tool_schemas() -> dict[str, ToolSchema]:
    return deepcopy(_DEFAULT_TOOL_SCHEMAS)
"""


def _schema_payload(fixture: dict[str, object]) -> dict[str, dict[str, object]]:
    tools = fixture.get("tools")
    if not isinstance(tools, list):
        raise ValueError("builtin_tools fixture must contain tools array")

    schemas: dict[str, dict[str, object]] = {}
    for tool in tools:
        if not isinstance(tool, dict):
            raise ValueError("builtin_tools fixture contains invalid tool")
        name = tool.get("name")
        tool_type = tool.get("type")
        description = tool.get("description")
        parameters = tool.get("parameters")
        if (
            not isinstance(name, str)
            or not isinstance(tool_type, str)
            or not isinstance(description, str)
            or not isinstance(parameters, dict)
        ):
            raise ValueError("builtin_tools fixture tool shape is invalid")
        schemas[name] = {
            "type": tool_type,
            "function": {
                "name": name,
                "description": description,
                "parameters": parameters,
            },
        }
    return schemas


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", type=Path, default=DEFAULT_FIXTURE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    fixture = json.loads(args.fixture.read_text(encoding="utf-8"))
    if not isinstance(fixture, dict):
        raise ValueError("builtin_tools fixture root must be an object")
    schemas = _schema_payload(fixture)
    rendered_schemas = pformat(schemas, width=sys.maxsize, sort_dicts=False)
    args.output.write_text(
        f"{HEADER}_DEFAULT_TOOL_SCHEMAS: dict[str, ToolSchema] = {rendered_schemas}{FOOTER}",
        encoding="utf-8",
    )
    subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--config",
            str(ROOT / "pyproject.toml"),
            str(args.output),
        ],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
    )


if __name__ == "__main__":
    main()
